baseurl = "http://andrewjorgensen.com"
title = "Andrew Jorgensen"
languageCode = "en-us"
theme = "hemingway"

contentdir = "content/post"
layoutdir = "layouts"
publishdir = "public"
canonifyurls = true

copyright = "&copy; <a href=\"https://andrewjorgensen.com\">Andrew Jorgensen</a> 2016"
googleAnalytics = "UA-51883548-1"

[params]

[params.highlight]
style = "github"
languages = ["go", "dockerfile"]

[[params.social]]
url = "https://github.com/ajorgensen"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/ajorgensen"
fa_icon = "fa-twitter"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"

