baseURL = "https://aj.codes/"
title = "Andrew Jorgensen"
languageCode = "en-us"

theme = "ajorgensen"
copyright = "© Andrew Jorgensen"
googleAnalytics = "UA-51883548-1"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    noclasses = false

# Pagination
paginate=2

[params]
	featherIconsCDN=true

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/ajorgensen/"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/ajorgensen/"

# Main menu Items

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 1
