baseURL = "https://aj.codes/"
title = "Andrew Jorgensen"
languageCode = "en-us"

theme = "ajorgensen"
copyright = "© Andrew Jorgensen"
enableRobotsTXT = true
defaultContentLanguage = 'en'

[params]
	featherIconsCDN=true
  Description = "My little corner of the internet. Thoughts and opinions are my own"
  TwitterHandle = "@ajorgensen"
  Image = "/images/cat.jpg"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    noclasses = false

# Pagination
paginate=2

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/ajorgensen/"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/ajorgensen/"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

# Main menu Items

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 1
