baseURL = 'https://aj.codes/'
languageCode = 'en-us'
title = 'Andrew Jorgensen'

[permalinks]
  posts = "blog/:slug/"

[params]
    generate_aliases = true

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = 'onedark'
    tabWidth = 4
    wrapperClass = 'highlight'
